In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Example 1: Shortest Path

In [14]:
def get_input(start, end):
    costMatrix = np.array([[0, 4, -1, -1, -1,-1, 6,-1],
                       [4, 0, 3, -1, -1,-1,-1, 3],
                       [-1, 3, 0, 5, -1,-1,-1,-1],
                       [-1, -1, 5, 0, 2,-1,-1, 5],
                       [-1, -1, -1, 2, 0, 3,-1, 4],
                       [-1, -1, -1, -1, 3, 0, 4,-1],
                       [ 6, -1, -1, -1, -1, 4, 0, 2],
                       [-1, 3, -1, 5, -5, -1, 2, 0]])
    return costMatrix[start - 1][end-1]

connections = {
    1 : [2, 7],
    2 : [1, 3, 8],
    3 : [2, 4],
    4 : [3, 5, 8],
    5 : [4, 6, 8],
    6 : [5, 7],
    7 : [1, 6, 8],
    8 : [2, 4, 5, 7]
}
    

In [34]:
# Formulate the N-horizontal problem

from math import inf


N = 1
g = np.zeros(N)
V = np.zeros(N)
V_current = []


start = 5

def value_iteration(start):
    passed_neighbours = []
    for neighbour in connections[start]:
        passed_neighbours.append(neighbour)
        V_current.append(g[k] + get_input(start, neighbour))
    to_choose = np.argmin(V_current)
    g[k] = V_current[to_choose]
    start = passed_neighbours[to_choose]
    
    passed_neighbours = []
    if start == 4:
        print("we are in goal")
        return g[k]
    else:
        print("we are in node ", start)
        return value_iteration(start)

for k in range(0,N):
    if  start == 4 :
        g[k] = 0
        print("we are in goal")
        continue 
    else:        
        g[k] = 100
    value_iteration(start)
    

print(g)

we are in goal
[102.]


In [41]:
costMatrix = np.array([[0, 4, -1, -1, -1,-1, 6,-1],
                       [4, 0, 3, -1, -1,-1,-1, 3],
                       [-1, 3, 0, 5, -1,-1,-1,-1],
                       [-1, -1, 5, 0, 2,-1,-1, 5],
                       [-1, -1, -1, 2, 0, 3,-1, 4],
                       [-1, -1, -1, -1, 3, 0, 4,-1],
                       [ 6, -1, -1, -1, -1, 4, 0, 2],
                       [-1, 3, -1, 5, -5, -1, 2, 0]])

costMatrix = costMatrix + np.eye(8) * 10

print(costMatrix)

[[10.  4. -1. -1. -1. -1.  6. -1.]
 [ 4. 10.  3. -1. -1. -1. -1.  3.]
 [-1.  3. 10.  5. -1. -1. -1. -1.]
 [-1. -1.  5. 10.  2. -1. -1.  5.]
 [-1. -1. -1.  2. 10.  3. -1.  4.]
 [-1. -1. -1. -1.  3. 10.  4. -1.]
 [ 6. -1. -1. -1. -1.  4. 10.  2.]
 [-1.  3. -1.  5. -5. -1.  2. 10.]]


In [42]:
def value_iteration(Vfunc, costMatrix, xf):
    n = len(costMatrix)
    J = -1*np.ones(n)
    Vnext = -1*np.ones(n)
    mustar = -1*np.ones(n)

    for xi in range(n):
        if xi == xf:
            Vnext[xi] = Vfunc[xi]
            mustar[xi] = xi
            continue
        for ui in range(n):
            if costMatrix[xi,ui] != -1:
                J[ui] = costMatrix[xi,ui] + Vfunc[ui]
            else:
                J[ui] = 10**6
        Vnext[xi] = np.min(J)
        mustar[xi] = np.argmin(J)
    return Vnext, mustar
    

In [55]:
n  = 8 
N  = 4
xf = 3
g  = 10**6*np.ones(n)
g[xf] = 0

V  = np.zeros((N,n))
mu = np.zeros((N,n))
V[0,:] = g

for j in range(N-1):
    V[j+1,:], mu[j+1,:] = value_iteration(V[j,:], costMatrix, xf)

In [62]:
print("V = ", V)
print("mu = ", mu)

V =  [[ 1.0e+06  1.0e+06  1.0e+06  0.0e+00  1.0e+06  1.0e+06  1.0e+06  1.0e+06]
 [ 1.0e+06  1.0e+06  5.0e+00  0.0e+00  2.0e+00  1.0e+06  1.0e+06  5.0e+00]
 [ 1.0e+06  8.0e+00  5.0e+00  0.0e+00  2.0e+00  5.0e+00  7.0e+00 -3.0e+00]
 [ 1.2e+01  0.0e+00  5.0e+00  0.0e+00  1.0e+00  5.0e+00 -1.0e+00 -3.0e+00]]
mu =  [[0. 0. 0. 0. 0. 0. 0. 0.]
 [2. 3. 3. 3. 3. 0. 1. 3.]
 [2. 2. 3. 3. 3. 4. 7. 4.]
 [1. 7. 3. 3. 7. 4. 7. 4.]]


In [61]:
# find the optimal path
x = -1*np.ones(N)
x[0] = 6
for k in range(N-1):
    x[k+1] = mu[N-1-k, int(x[k])]
print("x = ", x)

x =  [6. 7. 4. 3.]
