In [14]:
import numpy as np
import numpy.linalg as la

A = np.array([[2, 0, -2], [4, -2, 2], [0, 2, -2]])
B = np.array([[1], [0], [1]])

eig_desired = np.array([2, 4 - 3*1j, 4 + 3*1j])

# step 1: finding P
Delta_A = np.poly(A)

n = A.shape[0]

Bbar = np.zeros((n,1))
Bbar[-1] = 1

Abar = np.zeros((n,n))
Abar[:-1,1:] = np.eye(n-1)
Abar[-1,:] = - np.flip(Delta_A[1:Delta_A.shape[0] + 1])

Mc = np.block([B, A @ B, la.matrix_power(A,2) @ B])
Mcbar = np.block([Bbar, Abar @ Bbar, la.matrix_power(Abar,2) @ Bbar])
P = Mc @ la.inv(Mcbar)

resA = la.inv(P) @ A @ P
resB = la.inv(P) @ B

Delta_desired = np.poly(eig_desired)
Kbar = np.flip(Delta_desired[1:] - Delta_A[1:])

print(resA)
print(resB)

K = Kbar @ la.inv(Mcbar)

eig_res = la.eigvals(Abar - Bbar @ Kbar.reshape(1,3))

print(eig_res)

# print("K:", K)

[[-1.05471187e-15  1.00000000e+00 -1.66533454e-16]
 [ 1.99840144e-15 -1.33226763e-16  1.00000000e+00]
 [-1.60000000e+01  8.00000000e+00 -2.00000000e+00]]
[[ 0.00000000e+00]
 [-1.38777878e-17]
 [ 1.00000000e+00]]
[2.+0.j 4.+3.j 4.-3.j]


In [90]:
print(Delta_A   )
print(Abar[-1][:])
print(Delta_A[1:Delta_A.shape[0] + 1])
print(Mcbar)


[ 1.  2. -8. 16.]
[-16.   8.  -2.]
[ 2. -8. 16.]
[[ 0.  0.  1.]
 [ 0.  1. -2.]
 [ 1. -2. 12.]]
