In [3]:
import numpy as np
from pydrake.all import MathematicalProgram, Solve

In [4]:
def minimize_quadratic_cost(Q, A, b):

    n = Q.shape[0]
    m = A.shape[0]

    prog = MathematicalProgram()
    
    p = prog.NewContinuousVariables(n, "p")

    prog.AddQuadraticCost(Q, np.zeros(n), p)

    prog.AddLinearEqualityConstraint(A, b, p)

    result = Solve(prog)

    if result.is_success():
        p_opt = result.GetSolution(p)
        optimal_value = result.get_optimal_cost()
        return p_opt, optimal_value
    else:
        print("Solver failed:", result.get_solver_details().info)
        return None, None


In [5]:
T = 1
Q = np.array([[T**3/3, T**4/4],
                 [T**4/4, T**5/5]])
A = np.array([[1, 1]])
b = np.array([1])

minimize_quadratic_cost(Q, A, b)

(array([-1.5,  2.5]), 0.06250000000000001)

In [6]:
T = 1
Q = np.array([[T**3/3, T**4/4],
                 [T**4/4, T**5/5]])
A = np.array([[1, 1],
              [1, 2]])
b = np.array([1, -2])

minimize_quadratic_cost(Q, A, b)

(array([ 4., -3.]), 0.5666666666666663)

In [7]:
T = 1
Q = np.array([[T**3/3, T**4/4, T**5/5],
              [T**4/4, T**5/5, T**6/6],
              [T**5/5, T**6/6, T**7/7]])
A = np.array([[1, 1, 1]])
b = np.array([1])

minimize_quadratic_cost(Q, A, b)

(array([ 2., -8.,  7.]), 0.03333333333333363)

In [ ]:
T = 1
Q = np.array([[T**3/3, T**4/4, T**5/5],
              [T**4/4, T**5/5, T**6/6],
              [T**5/5, T**6/6, T**7/7]])
A = np.array([[1, 1, 1],
              [1, 2, 3]])
b = np.array([1, -2])

minimize_quadratic_cost(Q, A, b)

(array([-4.75, 14.5 , -8.75]), 0.20208333333333406)